### ISSUE TITLE
Visual editor nodes lose focus

### ISSUE THREAD

**Issue by mattbieber-lark** [statelyai/xstate-tools#166] opened 2022-06-19 22:43 UTC
Just noticed this today, but then I'm a bit new to the visual editor.  Selecting a node (Event, State) in the editor will focus it for a split second and then lose focus as if you had clicked out of the object.  I saw this mentioned by others in Discord so am logging an issue.  It _seems_ to have some correlation to the side panes having been opened.  Note:  I ruled out an extension conflict by disabling all but the Stately one. 

Macbook Pro w/ M1 chip

![2022-06-19 15 41 32](https://user-images.githubusercontent.com/79534219/174502990-ce8e63b8-a6b5-4807-882c-e6aa877545c9.gif)
.

**Comment by mattbieber-lark** [comment] 2022-06-21 06:05
no one?

**Comment by davidkpiano** [comment] 2022-06-21 10:25
This is only happening in the VS Code extension, correct?

**Comment by mattbieber-lark** [comment] 2022-06-21 17:13
Correct @davidkpiano. If it's not something affecting a bunch of people it's probably on my end.  I'll debug and post my findings here for others.

**Comment by bcdrme** [comment] 2022-09-05 08:05
I'm surprised no one else is talking about this issue. Not only does it lose focus when clicking nodes, but also when editing the machine. I think its every time it wants to save the machine in the .ts file, it loses focus.

It's very annoying, the vscode editor is barely usable.

**Comment by Andarist** [comment] 2022-09-05 08:54
> Not only does it lose focus when clicking nodes,

Could you try to record a short video that would showcase the problem? Or at least describe the whole scenario in detail? I would be interested in knowing where you click and what you expect to be focused and when.

> but also also when editing the machine.

Where do you edit it? Do you refer to the fact that touching the code of the machine might "unselect" the node in the Studio?

> I think its every time it wants to save the machine in the .ts file, it loses focus.

I can definitely see this happening, since I'm reworking the relevant parts of the code I will try to fix this while doing so.

**Comment by bcdrme** [comment] 2022-09-05 09:15
This is basically the same issue as OP's post.
Here I'm trying to type "Trying to name this state". As you can see, it loses focus. 

[Focus is lost](https://user-images.githubusercontent.com/54471255/188412517-a82c4899-46b7-40b7-969d-a31090afad31.webm)

I'm pretty sure the issue is : debounce on the input kicks off -> it triggers "generate the machine code" -> machine code is saved to the .ts file -> TS file has changed, reload the Studio.

In 1.9.0, a feature has been added : [#188](https://github.com/statelyai/xstate-tools/pull/188) [e54ce0d](https://github.com/statelyai/xstate-tools/commit/e54ce0d03040a62dd045ad892c9533305081109e) Thanks [@mellson](https://github.com/mellson)! - Changes made outside VS Code are now sent to the visual editor.

So, maybe its related ?

**Comment by davidkpiano** [comment] 2022-09-05 13:03
@bcdrme That's very likely the issue. The most probable fix is to avoid sending changes to VS Code until you've "committed" the change (e.g. by blurring the input).

**Comment by davidkpiano** [comment] 2022-09-05 13:13
Tracking in Linear: https://linear.app/statelyai/issue/STA-2201

**Comment by Andarist** [comment] 2022-11-08 16:13
I believe that I've fixed the issue in one of our dependencies that was causing this: https://github.com/chakra-ui/chakra-ui/pull/6863

**Closed by Andarist** 2022-11-08 16:13 UTC
