### ISSUE TITLE
VScode extension adds target property to events.

### ISSUE THREAD

**Issue by RafalFilipek** [statelyai/xstate-tools#98] opened 2022-03-09 20:24 UTC
Hi,

For some reason, any change made in visual editor causes adding `target` property on all events. For example:

![image](https://user-images.githubusercontent.com/80960/157528691-a8d7b081-8e1e-4e10-88c3-155a46e51af5.png)

After even moving anything, we will get something like this;

![image](https://user-images.githubusercontent.com/80960/157528955-128612c9-60d6-46d2-b9b6-d3d19db1d0b8.png)

```
VSCode: v1.65.1,
Xstate: v4.30.5
XState VSCode: v1.7.2
```

Thank you,

Rafał

**Comment by SimeonC** [comment] 2022-03-11 01:13
I've noticed this too - I think this is due to the editor forcing everything to be an "external" event. This actually causes bugs in some cases and can be worked around by using the "internal" toggle, but that ends up with more noise in the output IMO.

```
CHANGE_TITLE: {
  actions: "changeTitle",
  target: "#addPage.ready",
  internal: true
}
```

**Comment by mattpocock** [comment] 2022-03-11 09:10
@davidkpiano There's a design decision to be made here. We want to support self events, but we also want them to be able to be specified as 'external'. I guess we change the output so that self events print like this by default:

```
{ actions: ['whatever'] }
```

And like this if you specify `external: true`:

```
{ actions: ['whatever'], internal: false }
```

**Comment by Andarist** [comment] 2022-03-11 09:54
@mattpocock the proposed output is not accurate. For **targetless** transitions it doesn't matter if they are marked as internal or external - they should behave the same way. In this context, an **external** transition has to be one that defines a target explicitly.

See this here codesandbox that shows how `{ actions: ['whatever'], internal: false }` is not sufficient:
https://codesandbox.io/s/quiet-darkness-mmmzor?file=/src/index.js
and this codesandbox shows how the issue is fixed by adding a `target`:
https://codesandbox.io/s/laughing-noether-fos245?file=/src/index.js

As a side note - I really think that we should flip the default (including in v5) and make all transitions internal by default. At times external transitions can lead to surprising results, especially when we consider parallel states, but the situation with compound states isn't that much better either.

**Comment by mattpocock** [comment] 2022-03-11 12:02
FYI @RafalFilipek @SimeonC me and @Andarist had a private discussion on how to fix this, we have some ideas 👍

**Comment by davidkpiano** [comment] 2022-03-11 13:02
> @davidkpiano There's a design decision to be made here. We want to support self events, but we also want them to be able to be specified as 'external'. I guess we change the output so that self events print like this by default:
> 
> ```
> { actions: ['whatever'] }
> ```
> 
> And like this if you specify `external: true`:
> 
> ```
> { actions: ['whatever'], internal: false }
> ```

Yes, that makes sense 👍

**Comment by mattpocock** [comment] 2022-03-21 11:03
Made a PR for this in our closed-source repo.

**Closed** 2022-03-23 13:47 UTC
Labels: bug
