### ISSUE TITLE
Open Visual Editor is removing the `after` state properties

### ISSUE THREAD

**Issue by mdpratt** [statelyai/xstate-tools#253] opened 2022-11-19 12:18 UTC
This drove me bonkers for a few hours, since I opened the visual editor in a dependency in my node_modules, and didn't notice that the file changed.

Given an example state like below:

```typescript
pageable: {
  entry: 'sendPageReady',
  after: [{
    delay: (context) => context.settings.paginationDelay ?? 100,
    cond: 'isPaginationAutomatic',
    target: 'fetching'
  }],
  on: {
    PAGE: 'fetching',
    SEND_REQUEST: {
      cond: 'isValidSendRequest',
      target: 'assignNewRequest',
      actions: 'assignRequest'
    }
  }
}
```

Opening the visual editor will remove the `after` property and format it as such:

```typescript
pageable: {
  entry: "sendPageReady",
  on: {
    PAGE: {
      target: "fetching",
    },
    SEND_REQUEST: {
      target: "assignNewRequest",
      cond: "isValidSendRequest",
      actions: "assignRequest",
    },
  },
},
```

**Comment by ChandlerFerry** [comment] 2022-12-04 23:53
Had this issue myself, caught me off guard.

Further analysis shows that this is specifically caused by `delay: 'DELAY_NAME'`.

Utilizing delay names as keys works as intended as per the [example](https://github.com/statelyai/xstate-tools/blob/317b8f5baa7e4fa2ca4779ad6729251b1577daf1/packages/machine-extractor/examples/delays.machine.ts#L5-L11).
```
    after: {
      DELAY_NAME: {
        actions: () => {
          console.log('Yay');
        },
      },
    },
```

**Comment by davidkpiano** [comment] 2022-12-04 23:57
Very sorry about that. We are releasing a new version of the extension this week that should resolve these issues (cc. @Andarist)

**Comment by Andarist** [comment] 2022-12-06 16:34
@mdpratt could you confirm that this has been fixed with the latest release of the extension?

**Closed** 2022-12-13 14:41 UTC

**Comment by mdpratt** [comment] 2022-12-13 18:45
Hi @Andarist sorry I just saw this. I'll verify and reopen this issue if it's still causing problems.
